language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - 2.0.0
before_install:
  - sudo apt-get install -qq libicu-dev
script: bundle exec rspec spec
