language: ruby
bundler_args: --without development
before_install:
  - sudo apt-get install -qq libicu-dev
rvm:
  - 2.3.0
  - 2.4.0
matrix:
  allow_failures:
    - rvm: jruby
script: bundle exec rspec spec
